//created on: 20.10.2014
package messageRule

import org.hda.responseSelection.EventMessage;

rule "DDoS"
    when
        m : CMessage( status == CMessage.DDoS, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( CMessage.CuC );
        update( m );
end

rule "CuC"
    when
        CMessage( status == CMessage.CuC, myMessage : message )
    then
        System.out.println( myMessage );
end

